name: inputValidation

on: 
  workflow_dispatch:
    inputs:
      age:
        description: "Enter your age"
        required: true

jobs: 
  check_job:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run python script
        run: python main.py ${{github.event.inputs.age }}

      - name: Run pytest
        run: pytest
